name: CI/CD Docker Simple Build

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build i Push do GHCR (amd64 only)
    runs-on: ubuntu-latest

    steps:
      # 1. Pobieramy kod z repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Instalujemy Buildx (do docker/build-push-action)
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      # 3. Logujemy się do GitHub Container Registry (GHCR)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Budujemy i wypychamy obraz (tylko architektura amd64)
      - name: Build and push Docker image (amd64)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest

      # 5. Poniżej zakomentowany krok Trivy (skanowanie obrazu)
      # - name: Scan pushed image with Trivy
      #   uses: aquasecurity/trivy-action@0.12.0
      #   with:
      #     scan-type: image
      #     image-ref: ghcr.io/${{ github.repository }}:latest
      #     format: table
      #     exit-code: 1
      #     severity: HIGH,CRITICAL
      #     ignore-unfixed: true
